---

# main.yml

- hosts: default
  user: vagrant
  sudo: yes
  vars:
    httpd_port: 80
    mysql_port: 3306

  tasks:
    - name: update yum
      command: yum -y update

    # repository
    - name: add repository 'rpmforge-repo'
      yum: name=http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm state=present

    - name: add repository 'remi-repo'
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

    # include
    - include: editor.yml tags=editor
    - include: dev.yml    tags=dev


  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

    - name: restart iptables
      service: name=iptables state=restarted
